import { describe, expect, it } from "vitest"

import { parseCStudioChamiloResource } from "@/domain/learningPaths/cstudioResource"

describe("CStudio Chamilo resource metadata", () => {
  it("parses a quiz resource generated by CStudio", () => {
    expect(
      parseCStudioChamiloResource({
        resourceTool: "tests",
        resourceKey: "quiz:17",
        title: "Chapter test",
        launchUrl: "/resources/exercise/42/17/player?cid=10&origin=learnpath&embedded=1",
      }),
    ).toMatchObject({ type: "quiz", id: 17, title: "Chapter test" })
  })

  it("extracts the parent forum from a thread launch URL", () => {
    expect(
      parseCStudioChamiloResource({
        resourceTool: "forums",
        resourceKey: "thread:21",
        title: "General / Welcome",
        launchUrl: "/resources/forum/42/forum/8/thread/21?cid=10&embedded=1",
      }),
    ).toMatchObject({ type: "thread", id: 21, forumId: 8 })
  })

  it("rejects mismatched resource metadata", () => {
    expect(
      parseCStudioChamiloResource({
        resourceTool: "tests",
        resourceKey: "quiz:17",
        title: "Wrong target",
        launchUrl: "/resources/exercise/42/99/player?cid=10",
      }),
    ).toBeNull()
  })
})
